server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /demo


#spring:
#  application:
#    name: demo
#  # === 配置数据源 ===
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/xxxxx?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
#    username: root
#    password: police
#    type: com.alibaba.druid.pool.DruidDataSource
#    druid:
#      #初始化连接数
#      initial-size: 5
#      #最小连接数
#      min-idle: 5
#      #最大连接数
#      max-active: 20
#      max-wait: 60000
#      time-between-eviction-runs-millis: 60000
#      min-evictable-idle-time-millis: 300000
#      validation-query: select version()
#      test-while-idle: true
#      test-on-borrow: false
#      test-on-return: false
#      pool-prepared-statements: true
#      max-pool-prepared-statement-per-connection-size: 20
#      #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
#      #filters: stat,wall,log4j
#      filters: stat,wall
#      use-global-data-source-stat: true
#      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
#
#  # === 配置Redis ===
#  redis:
#    database: 1
#    host: 127.0.0.1
#    port: 6378
#    password:
#    timeout: 10s
#    jedis:
#      pool:
#        max-active: 1000
#        max-wait: 300s
#        max-idle: 8
#        min-idle: 0
#
#  # === 配置json ===
#  jackson:
#    # 全局时区
#    time-zone: GMT+8
#    # 序列化默认属性包含（non_null-仅存非null字段）
#    default-property-inclusion: non_null
#  servlet:
#    # === 附件上传 ===
#    multipart:
#      # 是否允许附件上传，默认参数为true
#      enabled: true
#      # 指定单个上传文件的最大长度。默认是1MB（-1代表不限制上传文件大小）
#      max-file-size: 5120MB
#      # 指定单个上传文件的最大长度。默认是1MB（-1代表不限制上传文件大小）
#      max-request-size: 5120MB
#
## === mybatis-plus相关配置 ===
#mybatis-plus:
#  # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
#  mapper-locations: classpath:mapper/*.xml
#  # 别名包扫描路径，通过该属性可以给包中的类注册别名
#  type-aliases-package: com.example.demo.entity
#  # 以下配置均有默认值,可以不设置
#  global-config:
#    db-config:
#      #主键类型  auto:"数据库ID自增" 1-input:"用户输入ID",2-id_worker:"全局唯一ID (数字类型唯一ID)", 3-uuid:"全局唯一ID UUID";
#      id-type: UUID
#      #字段策略 IGNORED:"忽略判断"  NOT_NULL:"非 NULL 判断")  NOT_EMPTY:"非空判断"
#      field-strategy: NOT_EMPTY
#      #数据库类型
#      db-type: MYSQL
#      # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置@TableLogic) -关联查询后会失效
#      logic-delete-field: isDel
#      # 逻辑已删除值(默认为 1)
#      logic-delete-value: 1
#      # 逻辑未删除值(默认为 0)
#      logic-not-delete-value: 0
#  configuration:
#    #不开启二级缓存
#    cache-enabled: false
#    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
#    map-underscore-to-camel-case: true
#    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，是否映射这个字段（true-映射，false-不映射），对 entity 类影响不大，对 Map 数据有影响
#    call-setters-on-nulls: true
#    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#        log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl

    # === 配置MinIo ===
#    minio:
#        endpoint: http://36.133.149.112:9001
#        accessKey: cocoa
#        secretKey: 8e6b3589269c1612210a22
#        bucketName: hz-assist